### ISSUE TITLE
Uncaught TypeError: onClickOutside is not a function

### ISSUE THREAD

**Issue by PendletonJones** [Pomax/react-onclickoutside#151] opened 2017-02-15 16:34 UTC
"react-onclickoutside": "^5.9.0",

```
const onClickOutside = require('react-onclickoutside');
console.log(onClickOutside);

```
<img width="201" alt="screen shot 2017-02-15 at 11 31 54 am" src="https://cloud.githubusercontent.com/assets/8836909/22984168/88a8fd0a-f372-11e6-9be7-e0abcd594a65.png">

Seems like it's an object and I get a TypeError when I try to use it. 

I have tried installing, uninstalling, and reinstalling with NPM and Yarn with the same results. 

Does anyone know how to require the HOC?

**Comment by Pomax** [comment] 2017-02-15 20:12
Can you try the following in a new temp dir:
```
npm init -y
npm install react react-dom react-onclickoutside
```
Which should say something like:
```
temp@1.0.0
+-- react@15.4.2
+-- react-dom@15.4.2
`-- react-onclickoutside@5.9.0
```
And then start up node and require the hoc:
```
node
require('react-onclickoutside')
```
This *should* say `[Function: onClickOutsideHOC]`. If it doesn't, something really weird is going on for you that I cannot reproduce.

**Comment by PendletonJones** [comment] 2017-02-15 20:29
I can confirm that it does work in a temp directory with your instructions. 
I am on 15.4.1 for both react and react-dom. 

Do you think this could be the issue?

**Comment by Pomax** [comment] 2017-02-15 20:32
It sounds far more like a preprocessor (webpack, require hook, etc) is doing something it shouldn't be doing, but the scientific method requires more debugging: what happens when you just fire up node on its own inside your normal project dir, and say `require('react-onclickoutside')`?

**Comment by PendletonJones** [comment] 2017-02-15 20:34
I get the HOC inside the normal project dir. This must be some kind of bundler issue.

**Comment by Pomax** [comment] 2017-02-15 20:36
In that case I will be closing this issue, but wish you much coffee for the process of running through all the webpack extensions and plugins that are in effect to figure out which is ruining the party... hopefully it's the first one, and then filing an issue on their issue tracker is only a few minutes work =)

**Closed by Pomax** 2017-02-15 20:36 UTC

**Comment by vjpr** [comment] 2017-02-28 16:09
I was getting the same issue using 4.9.0. It seems that webpack was using the AMD module definition which was not working correctly.

```
(function (root, factory) {
  if (true) {
    // AMD. Register as an anonymous module.
    !(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(35)], __WEBPACK_AMD_DEFINE_RESULT__ = function(reactDom) {
      return factory(root, reactDom);
    }.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__),
				__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
  } else if (typeof exports === 'object') {
    // Node. Note that this does not work with strict
    // CommonJS, but only CommonJS-like environments
    // that support module.exports
    module.exports = factory(root, require('react-dom'));
  } else {
    // Browser globals (root is window)
    root.OnClickOutside = factory(root, ReactDOM);
  }
}(this, function (root, ReactDOM) {
```

I will try upgrading to ^5.

**Comment by Pomax** [comment] 2017-02-28 16:35
@vjpr even if it turns out it still applies, please file a new issue instead, so the work can be track independently.
