### ISSUE TITLE
Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by Kimahriman** [Pomax/react-onclickoutside#193] opened 2017-05-27 19:59 UTC
I'm getting this error when trying to use this package:
```
Cannot read property 'getInstance' of undefined
```
It happens in `componentDidMount` when it tries to get the instance
```javascript
const instance = this.getInstance();`
```
it fails at 
```javascript
const ref = this.instanceRef;
return ref.getInstance ? ref.getInstance() : ref;
```
because `ref` is null. It looks like this is because `getInstance` is never bound to `this`, so it wouldn't have access to `this.instanceRef`, thus causing the error. Am I missing something here?

**Comment by Pomax** [comment] 2017-05-31 03:18
I can't tell off of the code in your question; do you have a self-contained minimal example of code that reproduces this?

**Comment by traviss-comvex** [comment] 2017-05-31 05:05
Same issue for me. I re-wrote my code as an HOC and still get the same error.

```
// Import libs up here

const toggleComponent = (WrappedComponent, defaultState = false) => {
    class ToggleComponent extends React.Component {
        constructor(props) {} // Omitted - Nothing fancy here

        handleClickOutside(evt) {
            console.log('handleClickOutside()', evt);
        }

        render() {
            return <WrappedComponent {...this.props} />;
        }
    }

    return onClickOutside(ToggleComponent);
}

export default toggleComponent;
```

My stateless component
```
// Import HOC and libs

const Dropdown = ({ open, toggle }) => {
    return (
        <div>some elements</div>
    );
}

export default toggleComponent(Dropdown);
```

**Comment by Andarist** [comment] 2017-05-31 11:14
@traviss-comvex I cant really reproduce ur issue with the provided code. I've pasted it quickly into the [codesandbox](https://codesandbox.io/s/68n0vQZyR) and everything is working fine

**Comment by traviss-comvex** [comment] 2017-06-01 00:56
@Andarist It appears you are correct, it must be something with my layout/architecture. Thanks for looking into it.

**Comment by Andarist** [comment] 2017-06-01 05:25
Let me know what was wrong. It seems that other ppl have similar problem judging by the emoji reactions

**Comment by traviss-comvex** [comment] 2017-06-01 07:36
I spent awhile this morning trying to get it work but to no avail. I tried the simplest component within my build but still got the same error. I haven't been able to narrow it down but I have a suspicion it is being cause by a parent component. In my case:

`<AppContainer />` React Hot Loader
`<Provider />` Redux
`<BrowserRouter />` React Router
`<Router />` React Router
`<Switch />` React Router
`<Route />` React Router

**Comment by Andarist** [comment] 2017-06-01 08:23
Could u share ur setup on something like codesandbox? Ofc ur app may be all stripped away - just leave the error in :trollface: I would be happy to help u debug this, it ofc still may be some problem in the lib itself

**Comment by Kimahriman** [comment] 2017-06-01 13:28
Ok I figured out it has to do with using Hot Module Replacement. Working on getting a repo up that is broken.

**Comment by Kimahriman** [comment] 2017-06-01 14:12
Ok repo is up: https://github.com/Kimahriman/onclickoutside-test

**Comment by Andarist** [comment] 2017-06-01 14:55
Thanks for the reproduced issue! HMR is messing with `this` here and doesnt proxy simple assignments like `this.instanceRef = ref` to the `ProxyComponent`, because `this` in the `getRef` callback is encapsulated in the `constructor` and it points to the original one.

Without implementation based on [`Proxy`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) there is no possibility for it to work as expected. We could mitigate this on our side in the lib itself as a temporary workaround (@Pomax WDYT?) and I'm gonna try to fix this on `react-proxy`'s side when I have some spare time.

**Comment by sontek** [comment] 2017-06-04 04:21
I just upgraded react-onclickoutside and ran into this issue as well.

```
git diff package.json |grep click
-    "react-onclickoutside": "5.9.0",
+    "react-onclickoutside": "^6.0.1",
```

is there a workaround or should I just stay on the old version?

**Comment by Pomax** [comment] 2017-06-05 19:58
It makes no sense to fix a problem with another library in this library. If this is an issue with react-proxy, then please file an issue there, and then link to that issue here so that people know where the problem is, and can jump into that issue to request a fix sooner than later.

@sontek in isolated code or also because of some other component?

**Comment by sontek** [comment] 2017-06-05 20:05
@Pomax `react-proxy` hasn't changed in over a year, nothing was broken until I upgraded `react-onclickoutside`, the version of `react-proxy` I'm using is the latest.

My usage is basically just:

```
class CustomComponent extends React.Component {
    handleClickOutside(e) {
        this.setState({
            showPicker: false
        });
    }
    render() {
        return (
            <div />
        );
    }
}

const ColorEditorSetting = onClickOutside(ColorEditorSettingCls);
```

I didn't dig into it much since I found this report that already described my problem but I can look into it more if it'd be useful.

**Comment by Pomax** [comment] 2017-06-05 20:18
Just trying to understand what is going on. Does the code you just showed cause a "Cannot read property 'getInstance' of undefined" in the console already? Or does it happen when you try to do something specific?

**Comment by Andarist** [comment] 2017-06-05 20:20
@sontek ive already done the digging and described the cause in some post above

The issue has surfaced just now as some parts of the code has changed in this lib, no real behaviour changes though and the code is perfectly valid. Problem is that react-proxy is not capable (yet) of proxying such code, I guess it doesnt surface as much as most libs and people transpile to es5 for u.

**Comment by Andarist** [comment] 2017-06-06 20:41
I've checked quickly the new version cause I had feeling that shipping transpiled version of the lib would restore `react-proxy`'s ability to proxy correctly - and it works 🎉 

@sontek please confirm, so the issue can be closed

**Comment by sontek** [comment] 2017-06-06 20:58
Yeah, that looks like its working for me as well

**Comment by Pomax** [comment] 2017-06-08 20:53
cool, in that case I'll close this as "fixed" with the new version.

**Closed by Pomax** 2017-06-08 20:53 UTC
