### ISSUE TITLE
handleClickOutside is called when clicked inside

### ISSUE THREAD

**Issue by kuzzmi** [Pomax/react-onclickoutside#144] opened 2016-11-10 20:49 UTC
I've been using `react-onclickoutside` for quite a while throughout the project, however in one particular case it glitches and calls `handleClickOutside()` when I click somewhere inside the wrapped component.

Here is a screenshot of React dev-tools. There is an expanded click event in the console window, which triggered an "outside" event and the target of this event is the wrapped element.

 ![](https://i.snag.gy/XZR0H2.jpg)

I've tried to debug this myself, but this led me to nowhere.

**Comment by Pomax** [comment] 2016-11-10 22:15
hm, a minimal PoC would be kind of necessary here. No luck at all reducing?

**Comment by kuzzmi** [comment] 2016-11-10 22:39
I tried reducing outside of the project, but no luck. As soon as I have a PoC I link it to the issue. 
If you don't want having hanging issues, you can close this one for now, we can reopen then.

**Comment by Pomax** [comment] 2016-11-10 22:40
hanging issues are cool, if someone else runs into the same problem and they have a PoC that works then there's a place for them to tack it on and everyone interested in solving it will get the notice =)

**Comment by kiejo** [comment] 2016-12-08 16:07
I had a similar issue with one of my components and it was caused by the component returning `null` under specific circumstances (the component could be shown or hidden). I was able work around the issue by not returning `null` in the `render` method and setting the `display` property to `none` instead.

**Comment by kuzzmi** [comment] 2016-12-08 16:22
@kiejo awesome! I absolutely forgot about this part in trying to reduce. This component was rendering `null` in some cases.

**Comment by Pomax** [comment] 2016-12-11 20:01
Good to hear you found a solution, although it feels like a stop-gap measure at best:

Using CSS to control the UI is the opposite of what a "Reacty" solution should be: you really *should* be returning `null` in your UI code because React doesn't actually care about the exact render engine; your users should see what your `render()` chain generates, so relying on CSS to "hide" something is making your UI explicitly tied to the DOM, which React is supposed to actually make irrelevant.

(following React's "if it's not in the UI, don't generate it" philosophy. CSS is for styling what you *can* see, not for hiding what you shouldn't - any data that you "would lose by removing that UI" is just component state, and isn't lost in the slightest if you do stateful components right; rendering them instead of returning `null` at some later point should immediately render that part of your UI with the state preserved and presented correctly to the user)

**Comment by kiejo** [comment] 2016-12-12 08:23
> Good to hear you found a solution, although it feels like a stop-gap measure at best, because it hacks around how UIs are supposed to work in React.

I agree and the intent of my comment was to provide a workaround and to help find out what the actual underlying issue is. The library should definitely not force users to change their CSS just to make the library work. So this issue still needs to be solved.

> Using CSS to control the UI is the opposite of what a "Reacty" solution should be.

I also agree that in most cases React is being used in the wrong way if CSS is used to control which components to render. Nevertheless, I think there are specific cases in the context of React where hiding components using CSS instead of returning `null` can be a better option. Here is what Ben Alpert from the React team has to say about this topic:
> In most cases it's better to not render the field at all, so that React doesn't need to consider it and no DOM nodes are created. (**If you're frequently toggling between a field being shown or not, hiding it temporarily can be a better option** so that it doesn't need to be recreated constantly,...).

https://discuss.reactjs.org/t/conditional-rendering-or-toggling-hidden-classes/2535

**Comment by Pomax** [comment] 2016-12-12 22:45
Yeah, good thread - though it's important to note that "frequently" basically means "several times a second". The cost of DOM node insertion is substantial, but not so substantial as to create a sluggish UI (at least not on modern browsers, not even mobile ones, provided we're talking IOS8+, android 6+, etc)

**Comment by yzgw** [comment] 2016-12-21 05:41
I had a similar issue, and tried writing a minimal PoC.
https://jsfiddle.net/xkgwuxhb/4/

**Comment by Pomax** [comment] 2016-12-21 17:49
Porting code from @yzgw's example over for analysis here:
```
const Popup = onClickOutside((props) => {
	if (props.hidden === true) {
		return null;
	}
	return <div className="popup">toolbox</div>;
});

class Widget extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showToolbox: false
    };
  }
  render() {
    return (
	    <div className="widget">
	      <button onClick={this.showToolbox}>show toolbox</button>
        <Popup hidden={!this.state.showToolbox} handleClickOutside={this.hideToolbox} />
        <div className="workspace">workspace</div>
      </div>
    );
	}
  showToolbox = (event) => {
    console.log("showToolbox");
  	this.setState({
    	showToolbox: true
    });
  };
  hideToolbox = (event) => {
    console.log("hideToolTools");
  	this.setState({
  		showToolbox: false
  	});
  };
}

ReactDOM.render(<Widget />, document.getElementById("container"));
```

**Comment by Pomax** [comment] 2016-12-21 19:23
further reduced example still showing this bug:
```
class BasePopup extends React.Component {
  constructor(props) {
    super(props);
  } 
	render(props) {
    return this.props.hidden? null : <div>toolbox</div>;
	}
  handleClickOutside(evt) {
	  this.props.hide();
	}
}

const Popup = onClickOutside(BasePopup);

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      hideToolbox: true
    }
  }
  render() {
		return (
	    <div>
	      <button onClick={e => this.show(e)}>show toolbox</button>
        <Popup hidden={this.state.hideToolbox} hide={e => this.hide(e)} />
      </div>
    );
	}
  show(event) {
  	this.setState({ hideToolbox: false });
  }
  hide(event) {
  	this.setState({ hideToolbox: true });
  }
}

ReactDOM.render(<App/>, document.getElementById("app"));
```

**Comment by Pomax** [comment] 2016-12-21 20:06
Analysis shows that the type of code provided by @yzgw fails due to not having an initial DOM node to hook into. By returning `null` in the render function when the component is first mounted, the HOC's `componentDidMount` handler cannot actually find a DOM node to use as reference node for the chain of elements inside of which an event is triggered.

The solution to this problem is to not make the component responsible for rendering itself as `null`, but to make the parent responsible for rendering the component *at all*. In this particular case, `Popup` should simply always render itself in the assumption it is visible, and `Widget`/`App` is responsible for deciding whether or not to even show the Popup at all.

A most-minimally rewritten jsbin showing this working just fine: https://jsfiddle.net/jkjnwhys/

A code example:
```
const Popup = onClickOutside((props) => {
  // if a render call occurs, the implication is that this component is visible.
  return <div className="popup">toolbox</div>;
});

class Widget extends React.Component {
  ...
  render() {
    // here we decide whether or not the Popup component should be seen by our user or not.
    return (
      <div className="widget">
         <button onClick={this.showToolbox}>show toolbox</button>
        { !this.state.showToolbox ? null : <Popup handleClickOutside={this.hideToolbox} />}
        <div className="workspace">workspace</div>
      </div>
    },
    ...
}
```

**Comment by Pomax** [comment] 2016-12-21 20:49
this issue has been addressed in v5.8.0 both in code, in console log warnings, and in a documentation update to the README.md

**Closed by Pomax** 2016-12-21 20:49 UTC

**Comment by vjustov** [comment] 2017-09-11 17:12
Hey, i seem to be having the same issue, but my component is (or atleast should not be) returning null, im trying to make a jsfiddle to encapsulate the issue, but cannot, also the link to the readme that you mention no longer works. do you have ny pointers that might guide me on my quest?

**Comment by Andarist** [comment] 2017-09-11 17:26
What version of the library do you use?

**Comment by vjustov** [comment] 2017-09-11 17:33
Im using 6.5.0

**Comment by Andarist** [comment] 2017-09-12 07:05
Your version shouldnt suffer from the mentioned problem with rendering `null`. This got fixed and that's why that link to the README isnt working anymore - the note got removed as outdated.

Could you recreate ur issue on something like codesandbox.io or share your repository so I could test it on the live code? Also please describe your issue in more details - beyond "i seem to be having the same issue", because that is not specific enough and in fact the issue might be different for you.
