### ISSUE TITLE
Support many components

### ISSUE THREAD

**Issue by liorbentov** [Pomax/react-onclickoutside#108] opened 2016-06-28 21:18 UTC
Hey, If I have a parent component that contains many instance of a component with react-onclickoutside,
could I be able to detect which one of the component is relevant?

**Comment by Pomax** [comment] 2016-06-30 21:27
Hm, maybe, but can you go into a little more detail so I understand the use-case and the component/code structure you're thinking of?

**Comment by liorbentov** [comment] 2016-07-03 07:01
Hey, let's say I have an edit component:
The edit component has 2 states: 1. Viewing state (the value is a anchor -
read only), 2. Editing state (the value is an input).  I can transfer from
1 to 2 by clicking on the anchor, and from 2 to 1 I can transfer in two
ways: a. click on "v" button next to the input, b. click outside from the
component.
When I have only one instance of this component on the page, the event
listener behaves well (according to what I want :-)), but when I have more
than one, the event listener does not know which component I referred to...
So I need to know if your library can help we with that.

Thanks!

On Fri, Jul 1, 2016 at 12:32 AM Mike Kamermans <notifications@github.com>
wrote:

> Hm, maybe, but can you go into a little more detail so I understand the
> use-case and the component/code structure you're thinking of?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Pomax/react-onclickoutside/issues/108#issuecomment-229793985>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIMHC2uBM3ej4GMeDQfJ2eYHdUbGzZHcks5qRDSwgaJpZM4JAjCt>
> .
>
-- 
Lior Shub
Frontend Developer
P: (+972) 546-378-787
<https://twitter.com/BlazeMeter>
<https://www.linkedin.com/company/2364558>

**Comment by Pomax** [comment] 2016-07-03 17:54
hm, this sounds like a thing worth figuring out, marking as enhancement, and will try to write a small set of components that exhibit this behaviour (unless you want to help by reducing the code you have to a minimal example and adding that to the bug so we can test on that directly)

**Comment by augbog** [comment] 2016-11-08 03:04
I believe this is a similar issue I faced. I made a demo repo of the issue [here](https://github.com/augbog/react-onclickoutside-issue-108).

So I think one way you can make the "outside" component away of what inner components are clicked is to go off the `event.target.id` but this is a really bad solution because if they click the children, it doesn't register. I'm also kind of curious if there is a cleaner way of handling this? In situations where you need to dynamically change what event happens when you click outside of a component but on another component, it can get really messy.

**Comment by Pomax** [comment] 2016-11-08 06:12
in terms of a reproducible example, a full compile is a bit overkill - I'd recommend a http://jsbin.com example with the javascript tab set to React, and then just include `https://rawgit.com/Pomax/react-onclickoutside/master/index.js` as a script to give you the HOC. No need for full clones with remotes, or webpack compiles, that way.

**Comment by Pomax** [comment] 2016-12-20 18:17
closing due to inactivity - feel free to refile (ideally with reproducible example code) if this becomes a problem again.

**Closed by Pomax** 2016-12-20 18:17 UTC
Labels: enhancement, help wanted
